unique_ids:
  assets:
    standard-page.html: VUQ6VRJBY72K4WVZXG7XJVUE23GJVL4H
    theme.css: Z3LXUJAL723HX4OS3XJVHFBLERYSC3WP
  forms:
    Form1: XSP3IPAQD2NXQ2X7W4E4HLA423BN6ZTE
  modules: {}
  scripts: {}
  server_modules: {}
